'''
https://codeforces.com/gym/106511/submission/373209449
'''
LUT = ['', 'A', 'AB', 'BAC', 'BDCA', 'CBEDA', 'CFEDBA', 'DCGFEBA', 'DHGFECBA', 'EDIHGFCBA', 'EJIHGFDCBA', 'FEKJIHGDCBA', 'FLKJIHGEDCBA', 'GFMLKJIHEDCBA', 'GNMLKJIHFEDCBA', 'HGONMLKJIFEDCBA', 'HPONMLKJIGFEDCBA', 'IHQPONMLKJGFEDCBA', 'IRQPONMLKJHGFEDCBA', 'JISRQPONMLKHGFEDCBA', 'JTSRQPONMLKIHGFEDCBA', 'KJUTSRQPONMLIHGFEDCBA', 'KVUTSRQPONMLJIHGFEDCBA', 'LKWVUTSRQPONMJIHGFEDCBA', 'LXWVUTSRQPONMKJIHGFEDCBA', 'MLYXWVUTSRQPONKJIHGFEDCBA', 'MZYXWVUTSRQPONLKJIHGFEDCBA']
def solve(n: int) -> str:
    return LUT[n]
    