# Submission link: https://codeforces.com/gym/106511/submission/373033800
def main():
    ans = ['', 'A', 'AB', 'BAC', 'BDCA', 'CBEDA', 'CFEDBA', 'DCGFEBA', 'DHGFECBA', 'EDIHGFCBA', 'EJIHGFDCBA', 'FEKJIHGDCBA', 'FLKJIHGEDCBA', 'GFMLKJIHEDCBA', 'GNMLKJIHFEDCBA', 'HGONMLKJIFEDCBA', 'HPONMLKJIGFEDCBA', 'IHQPONMLKJGFEDCBA', 'IRQPONMLKJHGFEDCBA', 'JISRQPONMLKHGFEDCBA', 'JTSRQPONMLKIHGFEDCBA', 'KJUTSRQPONMLIHGFEDCBA', 'KVUTSRQPONMLJIHGFEDCBA', 'LKWVUTSRQPONMJIHGFEDCBA', 'LXWVUTSRQPONMKJIHGFEDCBA', 'MLYXWVUTSRQPONKJIHGFEDCBA', 'MZYXWVUTSRQPONLKJIHGFEDCBA']
    
    t = II()
    outs = []
    
    for _ in range(t):
        outs.append(ans[II()])
    
    print('\n'.join(map(str, outs)))